//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/InputSystem/WeaponSwitchInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WeaponSwitchInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WeaponSwitchInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WeaponSwitchInput"",
    ""maps"": [
        {
            ""name"": ""Weapon"",
            ""id"": ""89b6ee0d-7186-413b-9b29-78ed0b537a88"",
            ""actions"": [
                {
                    ""name"": ""1"",
                    ""type"": ""Button"",
                    ""id"": ""aa8b8050-4398-4a90-a78a-477cfe28c9f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2"",
                    ""type"": ""Button"",
                    ""id"": ""214f9970-a9b2-494f-945b-8398de4cdd5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fb04a72a-d958-4a66-bec4-35d5db5809c4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""069136a2-c880-4554-9e8e-10340c747f7a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Weapon
        m_Weapon = asset.FindActionMap("Weapon", throwIfNotFound: true);
        m_Weapon__1 = m_Weapon.FindAction("1", throwIfNotFound: true);
        m_Weapon__2 = m_Weapon.FindAction("2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Weapon
    private readonly InputActionMap m_Weapon;
    private IWeaponActions m_WeaponActionsCallbackInterface;
    private readonly InputAction m_Weapon__1;
    private readonly InputAction m_Weapon__2;
    public struct WeaponActions
    {
        private @WeaponSwitchInput m_Wrapper;
        public WeaponActions(@WeaponSwitchInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @_1 => m_Wrapper.m_Weapon__1;
        public InputAction @_2 => m_Wrapper.m_Weapon__2;
        public InputActionMap Get() { return m_Wrapper.m_Weapon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponActions set) { return set.Get(); }
        public void SetCallbacks(IWeaponActions instance)
        {
            if (m_Wrapper.m_WeaponActionsCallbackInterface != null)
            {
                @_1.started -= m_Wrapper.m_WeaponActionsCallbackInterface.On_1;
                @_1.performed -= m_Wrapper.m_WeaponActionsCallbackInterface.On_1;
                @_1.canceled -= m_Wrapper.m_WeaponActionsCallbackInterface.On_1;
                @_2.started -= m_Wrapper.m_WeaponActionsCallbackInterface.On_2;
                @_2.performed -= m_Wrapper.m_WeaponActionsCallbackInterface.On_2;
                @_2.canceled -= m_Wrapper.m_WeaponActionsCallbackInterface.On_2;
            }
            m_Wrapper.m_WeaponActionsCallbackInterface = instance;
            if (instance != null)
            {
                @_1.started += instance.On_1;
                @_1.performed += instance.On_1;
                @_1.canceled += instance.On_1;
                @_2.started += instance.On_2;
                @_2.performed += instance.On_2;
                @_2.canceled += instance.On_2;
            }
        }
    }
    public WeaponActions @Weapon => new WeaponActions(this);
    public interface IWeaponActions
    {
        void On_1(InputAction.CallbackContext context);
        void On_2(InputAction.CallbackContext context);
    }
}
